# Matrix Algebra

* Jacobi Iteration
* Gauss-Seidel Method
* Back Substitution
* Forward Substitution
* Gauss-Jordan Elimination
* LU Decomposition (Without Explicit Pivoting)
* Matrix Inversion
* Cholesky Decomposition

In [3]:
# Basic Imports
import numpy as np, scipy as sc

## Matrix Equation: AX = B

## 1. Jacobi Iteration

#### Iterative Formula:

For a $N$ by $N$ matrix, $A = D + R$, where $D$ contains diagonal elements of $A$, and $R$ contains all other elements of $A$, but with all diagonal elements, set to 0.

$$\mathbf {x} ^{(k+1)}=D^{-1}\left(\mathbf {B} -R\mathbf {x} ^{(k)}\right)$$

$$\boxed{x_{i}^{(k+1)}={\frac {1}{a_{ii}}}\left(b_{i}-\sum^{N-1}_{j\neq i}a_{ij}x_{j}^{(k)}\right),\quad i=0,1,\ldots (N-1)}$$
Therefore,

$$x_0^{(k+1)} = {\frac {1}{a_{00}}}\left(b_{0} - a_{01}x_{1}^{(k)} - a_{02}x_{2}^{(k)} - a_{03}x_{3}^{(k)}\ldots\right)$$

$$x_1^{(k+1)} = {\frac {1}{a_{11}}}\left(b_{1} - a_{10}x_{0}^{(k)} - a_{12}x_{2}^{(k)} - a_{13}x_{3}^{(k)}\ldots\right)$$

$$x_2^{(k+1)} = {\frac {1}{a_{22}}}\left(b_{2} - a_{20}x_{0}^{(k)} - a_{21}x_{1}^{(k)} - a_{23}x_{3}^{(k)}\ldots\right)$$

$$x_3^{(k+1)} = {\frac {1}{a_{33}}}\left(b_{3} - a_{30}x_{0}^{(k)} - a_{31}x_{1}^{(k)} - a_{32}x_{2}^{(k)}\ldots\right)$$
And so on...

#### Merits:


#### Demerits:

* Does not guarantee convergence

#### Notes: (From Wikipedia: https://en.wikipedia.org/wiki/Jacobi_method)

* The standard convergence condition (for any iterative method) is when the spectral radius of the iteration matrix is less than 1: $\rho (D^{-1}R)<1$.
* A sufficient (but not necessary) condition for the method to converge is that the matrix A is strictly or irreducibly diagonally dominant. Strict row diagonal dominance means that for each row, the absolute value of the diagonal term is greater than the sum of absolute values of other terms: $\left|a_{ii}\right|>\sum _{j\neq i}{\left|a_{ij}\right|}$.

In [4]:
def jacobi_iter(A, B, init_val, iter_lim, tol):
    """
    # A: N by N np.array() | Contains coefficients of the variables (Matrix, A)
    # B: N by 1 np.array() | Contains the constants on RHS (Vector, B)
    # init_val: np.array() | Contains Initial Values
    # iter_lim: Stores Iteration Limit
    # tol: Tolerance value - how precise does the solution need to be
    """
    CONV_FLAG = False # Convergence Flag
    ITER_LIM = iter_lim
    var = init_val # Vector, X
    
    print("System of Linear Equations:\n")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j) for j in range(A.shape[1])]
        print(" + ".join(row), "=", B[i])

    print("\nIteration Limit: ", ITER_LIM, "\n")
    
    for i in range(ITER_LIM):
        print("Iteration: {} | Current Solution: {}".format(i, var))
        var_new = np.zeros_like(var) # stores updated values of all variables (Vector, X)

        for j in range(A.shape[0]):
            # Matrix Multiplying all elements, before A's diagonal (in a row) with all corresponding vars (in Vector, X)
            d = np.dot(A[j, :j], var[:j])
            # Matrix Multiplying all elements, after A's diagonal (in a row) with all corresponding vars (in Vector, X)
            r = np.dot(A[j, j + 1:], var[j + 1:])
            # Updating values of vars
            var_new[j] = (B[j] - d - r)/A[j, j]
        
        # Checks, how close the updated values are, to the previous iteration's values and breaks the loop, if close enough (defined by "tol")
        if np.allclose(var, var_new, atol=tol, rtol=0.):
            print("\nSolution converged, after {} iterations.".format(i))
            CONV_FLAG = True
            break

        var = var_new # Storing the new solution
    # If solution is not obtained (no convergence), after ITER_LIM iterations | Note that, this "else" block belongs to the previous "for" statement and not any "if" statement
    else:
        CONV_FLAG = False

    # If Solution converged
    if CONV_FLAG:
        print("\nSOLUTION: ", var)
        print("ERROR: ", np.dot(A, var) - B) # Error in the obtained solution
    else:
        print("\nSolution did not converge, after the specified limit of {} iterations.".format(ITER_LIM))


# Testing the procedure
A = np.array([[4., -1., 1.],
              [4., -8., 1.],
              [-2., 1., 5.]])

B = np.array([7., 21., 15.])

jacobi_iter(A, B, init_val=[0.,0.,0.], iter_lim=120, tol=1e-10)

System of Linear Equations:

4.0x0 + -1.0x1 + 1.0x2 = 7.0
4.0x0 + -8.0x1 + 1.0x2 = 21.0
-2.0x0 + 1.0x1 + 5.0x2 = 15.0

Iteration Limit:  120 

Iteration: 0 | Current Solution: [0.0, 0.0, 0.0]
Iteration: 1 | Current Solution: [ 1.75  -2.625  3.   ]
Iteration: 2 | Current Solution: [ 0.34375 -1.375    4.225  ]
Iteration: 3 | Current Solution: [ 0.35   -1.925   3.4125]
Iteration: 4 | Current Solution: [ 0.415625  -2.0234375  3.525    ]
Iteration: 5 | Current Solution: [ 0.36289062 -1.9765625   3.5709375 ]
Iteration: 6 | Current Solution: [ 0.363125   -1.9971875   3.54046875]
Iteration: 7 | Current Solution: [ 0.36558594 -2.00087891  3.5446875 ]
Iteration: 8 | Current Solution: [ 0.3636084  -1.99912109  3.54641016]
Iteration: 9 | Current Solution: [ 0.36361719 -1.99989453  3.54526758]
Iteration: 10 | Current Solution: [ 0.36370947 -2.00003296  3.54542578]
Iteration: 11 | Current Solution: [ 0.36363531 -1.99996704  3.54549038]
Iteration: 12 | Current Solution: [ 0.36363564 -1.99999604  3.54

## 2. Gauss-Seidel Method

#### Iterative Formula:

For a $N$ by $N$ matrix, $A = L_* + U$, where $L_*$ contains lower triangular elements of $A$, and $U$ (a strictly upper triangular matrix) contains all other elements of $A$.

$$\mathbf {x} ^{(k+1)}=L_{*}^{-1}(\mathbf {b} -U\mathbf {x} ^{(k)})$$

$$\boxed{{\displaystyle x_{i}^{(k+1)}={\frac {1}{a_{ii}}}\left(b_{i}-\sum _{j=0}^{i-1}a_{ij}x_{j}^{(k+1)}-\sum _{j=i+1}^{N-1}a_{ij}x_{j}^{(k)}\right),\quad i=0,1\dots ,(N-1).}}$$
Therefore,

$$x_0^{(k+1)} = {\frac {1}{a_{00}}}\left(b_{0} - a_{01}x_{1}^{(k)} - a_{02}x_{2}^{(k)} - a_{03}x_{3}^{(k)}\ldots\right)$$

$$x_1^{(k+1)} = {\frac {1}{a_{11}}}\left(b_{1} - a_{10}x_{0}^{(k+1)} - a_{12}x_{2}^{(k)} - a_{13}x_{3}^{(k)}\ldots\right)$$

$$x_2^{(k+1)} = {\frac {1}{a_{22}}}\left(b_{2} - a_{20}x_{0}^{(k+1)} - a_{21}x_{1}^{(k+1)} - a_{23}x_{3}^{(k)}\ldots\right)$$

$$x_3^{(k+1)} = {\frac {1}{a_{33}}}\left(b_{3} - a_{30}x_{0}^{(k+1)} - a_{31}x_{1}^{(k+1)} - a_{32}x_{2}^{(k+1)}\ldots\right)$$
And so on...

#### Merits:

* Faster than Jacobi Iteration
* Same space complexity as Jacobi Iteration

#### Demerits:

* Does not guarantee convergence

In [5]:
def gauss_seidel(A, B, init_val, iter_lim, tol):
    """
    # A: N by N np.array() | Contains coefficients of the variables (Matrix, A)
    # B: N by 1 np.array() | Contains the constants on RHS (Vector, B)
    # init_val: np.array() | Contains Initial Values
    # iter_lim: Stores Iteration Limit
    # tol: Tolerance value - how precise does the solution need to be
    """
    CONV_FLAG = False # Convergence Flag
    ITER_LIM = iter_lim
    var = init_val # Vector, X
    
    print("System of Linear Equations:\n")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j) for j in range(A.shape[1])]
        print(" + ".join(row), "=", B[i])

    print("\nIteration Limit: ", ITER_LIM, "\n")
    
    for i in range(ITER_LIM):
        print("Iteration: {} | Current Solution: {}".format(i+1, var))
        var_new = np.zeros_like(var) # stores updated values of all variables (Vector, X)

        for j in range(A.shape[0]):
            # Matrix Multiplying all elements, before A's diagonal (in a row) with all corresponding vars (in Vector, X), that now have updated values
            l = np.dot(A[j, :j], var_new[:j]) # Note, the only change from jacobi_iter() is changing "var" to "var_new"
            # Matrix Multiplying all elements, after A's diagonal (in a row) with all corresponding vars (in Vector, X), that do not have updated values yet
            u = np.dot(A[j, j + 1:], var[j + 1:])
            # Updating values of vars
            var_new[j] = (B[j] - l - u) / A[j, j]
        
        # Checks, how close the updated values are, to the previous iteration's values and breaks the loop, if close enough (defined by "tol")
        if np.allclose(var, var_new, atol=tol, rtol=0.):
            print("\nSolution converged, after {} iterations.".format(i))
            CONV_FLAG = True
            break

        var = var_new # Storing the new solution
    # If solution is not obtained (no convergence), after ITER_LIM iterations | Note that, this "else" block belongs to the previous "for" statement and not any "if" statement
    else:
        CONV_FLAG = False

    # If Solution converged
    if CONV_FLAG:
        print("\nSOLUTION: ", var)
        print("ERROR: ", np.dot(A, var) - B) # Error in the obtained solution
    else:
        print("\nSolution did not converge, after the specified limit of {} iterations.".format(ITER_LIM))


# Testing the procedure
A = np.array([[4., -1., 1.],
              [4., -8., 1.],
              [-2., 1., 5.]])

B = np.array([7., 21., 15.])

gauss_seidel(A, B, init_val=[0.,0.,0.], iter_lim=120, tol=1e-10)

System of Linear Equations:

4.0x0 + -1.0x1 + 1.0x2 = 7.0
4.0x0 + -8.0x1 + 1.0x2 = 21.0
-2.0x0 + 1.0x1 + 5.0x2 = 15.0

Iteration Limit:  120 

Iteration: 1 | Current Solution: [0.0, 0.0, 0.0]
Iteration: 2 | Current Solution: [ 1.75 -1.75  4.05]
Iteration: 3 | Current Solution: [ 0.3     -1.96875  3.51375]
Iteration: 4 | Current Solution: [ 0.379375   -1.99609375  3.55096875]
Iteration: 5 | Current Solution: [ 0.36323437 -1.99951172  3.54519609]
Iteration: 6 | Current Solution: [ 0.36382305 -1.99993896  3.54551701]
Iteration: 7 | Current Solution: [ 0.36363601 -1.99999237  3.54545288]
Iteration: 8 | Current Solution: [ 0.36363869 -1.99999905  3.54545528]
Iteration: 9 | Current Solution: [ 0.36363642 -1.99999988  3.54545454]
Iteration: 10 | Current Solution: [ 0.36363639 -1.99999999  3.54545455]
Iteration: 11 | Current Solution: [ 0.36363637 -2.          3.54545455]
Iteration: 12 | Current Solution: [ 0.36363636 -2.          3.54545455]
Iteration: 13 | Current Solution: [ 0.36363636 -2. 

## 3. Back-Substitution Method

#### Iterative Formula:

For a $N$ by $N$ matrix, $A = D + U$, where $D$ is a diagonal matrix, containing all diagonal elements of $A$, while $U$ is a strictly upper triangular matrix, containing all other elements of $A$.

$$\mathbf {x} ^{(k+1)}=D^{-1}(\mathbf {b} -U\mathbf {x} ^{(k)})$$

$$\boxed{{\displaystyle x_{i}^{(k+1)}={\frac {1}{a_{ii}}}\left(b_{i}-\sum _{j=i+1}^{N-1}a_{ij}x_{j}^{(k)}\right),\quad i=0,1\dots ,(N-1).}}$$
Therefore,

$$x_0^{(k+1)} = {\frac {1}{a_{00}}}\left(b_{0} - a_{01}x_{1}^{(k)} - a_{02}x_{2}^{(k)} - a_{03}x_{3}^{(k)}\ldots\right)$$

$$x_1^{(k+1)} = {\frac {1}{a_{11}}}\left(b_{1} - a_{12}x_{2}^{(k)} - a_{13}x_{3}^{(k)}\ldots\right)$$

$$x_2^{(k+1)} = {\frac {1}{a_{22}}}\left(b_{2} - a_{23}x_{3}^{(k)}\ldots\right)$$

$$x_3^{(k+1)} = {\frac {1}{a_{33}}}\left(b_{3}\right)$$
And so on...

#### Merits:

* Much faster than Jacobi Iteration
* Same space complexity as Jacobi Iteration

#### Demerits:

* Does not guarantee convergence
* Works only for Upper Triangular Coefficient Matrices

In [6]:
def back_sub(A, B, init_val, iter_lim=100, tol=1e-8):
    """
    # A: N by N np.array() | Contains coefficients of the variables (Matrix, A)
    # B: N by 1 np.array() | Contains the constants on RHS (Vector, B)
    # init_val: np.array() | Contains Initial Values
    # iter_lim: Stores Iteration Limit | Default = 100
    # tol: Tolerance value - how precise does the solution need to be | Default = 1e-8
    """
    CONV_FLAG = False # Convergence Flag
    ITER_LIM = iter_lim
    var = init_val # Vector, X
    
    print("\nSOLVER: BACK_SUB\n\nSystem of Linear Equations:\n")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j) for j in range(A.shape[1])]
        print(" + ".join(row), "=", B[i])

    print("\nIteration Limit: ", ITER_LIM, "\n")
    
    for i in range(ITER_LIM):
        print("Iteration: {} | Current Solution: {}".format(i+1, var))
        var_new = np.zeros_like(var) # stores updated values of all variables (Vector, X)

        for j in range(A.shape[0]):
            # Matrix Multiplying all elements, after A's diagonal (in a row) with all corresponding vars (in Vector, X)
            u = np.dot(A[j, j + 1:], var[j + 1:])
            # Updating values of vars
            var_new[j] = (B[j] - u) / A[j, j]
        
        # Checks, how close the updated values are, to the previous iteration's values and breaks the loop, if close enough (defined by "tol")
        if np.allclose(var, var_new, atol=tol, rtol=0.):
            print("\nSolution converged, after {} iterations.".format(i))
            CONV_FLAG = True
            break

        var = var_new # Storing the new solution
    # If solution is not obtained (no convergence), after ITER_LIM iterations | Note that, this "else" block belongs to the previous "for" statement and not any "if" statement
    else:
        CONV_FLAG = False

    # If Solution converged
    if CONV_FLAG:
        print("\nSOLUTION: ", var)
        print("ERROR: ", np.dot(A, var) - B) # Error in the obtained solution
    else:
        print("\nSolution did not converge, after the specified limit of {} iterations.".format(ITER_LIM))
    
    return var

# Testing the procedure
A = np.array([[4., -1., 2., 3.],
              [0., -2., 7., -4.],
              [0., 0., 6., 5.],
              [0., 0., 0., 1.]])

B = np.array([20., -7., 4., 1.])

back_sub(A, B, init_val=[0.,0.,0.,0.], iter_lim=120, tol=1e-10)


SOLVER: BACK_SUB

System of Linear Equations:

4.0x0 + -1.0x1 + 2.0x2 + 3.0x3 = 20.0
0.0x0 + -2.0x1 + 7.0x2 + -4.0x3 = -7.0
0.0x0 + 0.0x1 + 6.0x2 + 5.0x3 = 4.0
0.0x0 + 0.0x1 + 0.0x2 + 1.0x3 = 1.0

Iteration Limit:  120 

Iteration: 1 | Current Solution: [0.0, 0.0, 0.0, 0.0]
Iteration: 2 | Current Solution: [5.         3.5        0.66666667 1.        ]
Iteration: 3 | Current Solution: [ 4.79166667  3.83333333 -0.16666667  1.        ]
Iteration: 4 | Current Solution: [ 5.29166667  0.91666667 -0.16666667  1.        ]
Iteration: 5 | Current Solution: [ 4.5625      0.91666667 -0.16666667  1.        ]

Solution converged, after 4 iterations.

SOLUTION:  [ 4.5625      0.91666667 -0.16666667  1.        ]
ERROR:  [0. 0. 0. 0.]


array([ 4.5625    ,  0.91666667, -0.16666667,  1.        ])

## 4. Forward-Substitution Method

#### Iterative Formula:

For a $N$ by $N$ matrix, $A = D + L$, where $D$ is a diagonal matrix, containing all diagonal elements of $A$, while $L$ is a strictly lower triangular matrix, containing all other elements of $A$.

$$\mathbf {x} ^{(k+1)}=D^{-1}(\mathbf {b} -L\mathbf {x} ^{(k)})$$

$$\boxed{{\displaystyle x_{i}^{(k+1)}={\frac {1}{a_{ii}}}\left(b_{i}-\sum _{j=0}^{i-1}a_{ij}x_{j}^{(k)}\right),\quad i=0,1\dots ,(N-1).}}$$
Therefore,

$$x_0^{(k+1)} = {\frac {1}{a_{00}}}\left(b_{0}\right)$$

$$x_1^{(k+1)} = {\frac {1}{a_{11}}}\left(b_{1} - a_{10}x_{0}^{(k+1)}\right)$$

$$x_2^{(k+1)} = {\frac {1}{a_{22}}}\left(b_{2} - a_{20}x_{0}^{(k+1)} - a_{21}x_{1}^{(k+1)}\right)$$

$$x_3^{(k+1)} = {\frac {1}{a_{33}}}\left(b_{3} - a_{30}x_{0}^{(k+1)} - a_{31}x_{1}^{(k+1)} - a_{32}x_{2}^{(k+1)}\right)$$
And so on...

#### Merits:

* Much faster than Jacobi Iteration
* Same space complexity as Jacobi Iteration

#### Demerits:

* Does not guarantee convergence
* Works only for Lower Triangular Coefficient Matrices

In [7]:
def forward_sub(A, B, init_val, iter_lim=100, tol=1e-8):
    """
    # A: N by N np.array() | Contains coefficients of the variables (Matrix, A)
    # B: N by 1 np.array() | Contains the constants on RHS (Vector, B)
    # init_val: np.array() | Contains Initial Values
    # iter_lim: Stores Iteration Limit | Default = 100
    # tol: Tolerance value - how precise does the solution need to be | Default = 1e-8
    """
    CONV_FLAG = False # Convergence Flag
    ITER_LIM = iter_lim
    var = init_val # Vector, X
    
    print("\nSOLVER: FORWARD_SUB\n\nSystem of Linear Equations:\n")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j) for j in range(A.shape[1])]
        print(" + ".join(row), "=", B[i])

    print("\nIteration Limit: ", ITER_LIM, "\n")
    
    for i in range(ITER_LIM):
        print("Iteration: {} | Current Solution: {}".format(i+1, var))
        var_new = np.zeros_like(var) # stores updated values of all variables (Vector, X)

        for j in range(A.shape[0]):
            # Matrix Multiplying all elements, after A's diagonal (in a row) with all corresponding vars (in Vector, X)
            l = np.dot(A[j, :j], var[:j])
            # Updating values of vars
            var_new[j] = (B[j] - l) / A[j, j]
        
        # Checks, how close the updated values are, to the previous iteration's values and breaks the loop, if close enough (defined by "tol")
        if np.allclose(var, var_new, atol=tol, rtol=0.):
            print("\nSolution converged, after {} iterations.".format(i))
            CONV_FLAG = True
            break

        var = var_new # Storing the new solution
    # If solution is not obtained (no convergence), after ITER_LIM iterations | Note that, this "else" block belongs to the previous "for" statement and not any "if" statement
    else:
        CONV_FLAG = False

    # If Solution converged
    if CONV_FLAG:
        print("\nSOLUTION: ", var)
        print("ERROR: ", np.dot(A, var) - B) # Error in the obtained solution
    else:
        print("\nSolution did not converge, after the specified limit of {} iterations.".format(ITER_LIM))
        
    return var


# Testing the procedure
A = np.array([[1., 0., 0., 0.],
              [5., 6., 0., 0.],
              [-4., 7., -2., 0.],
              [3., 2., -1., 4.]])

B = np.array([1., 4., -7., 20.])

forward_sub(A, B, init_val=[0.,0.,0.,0.], iter_lim=120, tol=1e-10)


SOLVER: FORWARD_SUB

System of Linear Equations:

1.0x0 + 0.0x1 + 0.0x2 + 0.0x3 = 1.0
5.0x0 + 6.0x1 + 0.0x2 + 0.0x3 = 4.0
-4.0x0 + 7.0x1 + -2.0x2 + 0.0x3 = -7.0
3.0x0 + 2.0x1 + -1.0x2 + 4.0x3 = 20.0

Iteration Limit:  120 

Iteration: 1 | Current Solution: [0.0, 0.0, 0.0, 0.0]
Iteration: 2 | Current Solution: [1.         0.66666667 3.5        5.        ]
Iteration: 3 | Current Solution: [ 1.         -0.16666667  3.83333333  4.79166667]
Iteration: 4 | Current Solution: [ 1.         -0.16666667  0.91666667  5.29166667]
Iteration: 5 | Current Solution: [ 1.         -0.16666667  0.91666667  4.5625    ]

Solution converged, after 4 iterations.

SOLUTION:  [ 1.         -0.16666667  0.91666667  4.5625    ]
ERROR:  [0. 0. 0. 0.]


array([ 1.        , -0.16666667,  0.91666667,  4.5625    ])

## 5. Gauss-Jordan Elimination

There are three types of elementary row operations which may be performed on the rows of a matrix:

* Swap the positions of two rows.
* Multiply a row by a non-zero scalar.
* Add to one row a scalar multiple of another.

Using these operations, we can convert the matrix, A, into "row-reduced echelon form", that can directly give us the solution for the system of linear equations.

#### References: https://en.m.wikipedia.org/wiki/Gaussian_elimination

In [8]:
def gauss_elim(A, B):
    """
    # A: N by N np.array() | Contains coefficients of the variables (Matrix, A)
    # B: N by 1 np.array() | Contains the constants on RHS (Vector, B)
    """
    # Prepping the Augmented Matrix
    aug_mat = np.concatenate((A, np.reshape(B, (-1, 1))), axis=1)
    # Convergence Flag
    CONV_FLAG = True
    # Position of leading nonzero, nondiagonal-element in a row
    lead = 0
    
    # aug_mat.shape[0] == No. of rows
    # aug_mat[0].shape or aug_mat.shape[1] == Number of Columns
    rowCount = aug_mat.shape[0]
    columnCount = aug_mat.shape[1]
    
    for r in range(rowCount):
        if lead >= columnCount:
            CONV_FLAG = False
            break
        i = r
        
        # Finding the leading nonzero element in a column
        while aug_mat[i][lead] == 0:
            i += 1
            if i == rowCount:
                i = r
                lead += 1
                if columnCount == lead:
                    CONV_FLAG = False
                    break
        
        aug_mat[i], aug_mat[r] = aug_mat[r], aug_mat[i] # Swapping rows
        lv = aug_mat[r][lead]
        aug_mat[r] = [mrx / float(lv) for mrx in aug_mat[r]]
        for i in range(rowCount):
            if i != r:
                lv = aug_mat[i][lead]         
                aug_mat[i] = [iv - lv*rv for rv,iv in zip(aug_mat[r], aug_mat[i])]
        lead += 1
        
    if CONV_FLAG:
        print("Solution = ", aug_mat[:, 3])
    else:
        print("Solution did not converge.")


# Testing the Procedure
A = np.array([[4., -1., 1.],
              [4., -8., 1.],
              [-2., 1., 5.]])

B = np.array([7., 21., 15.])

gauss_elim(A, B)

Solution =  [ 0.36363636 -2.          3.54545455]


## 6. LU Decomposition

### Using the algorithm mentioned here: https://math.stackexchange.com/questions/404419/lu-decomposition-steps

* Extension of Gaussian Elimintation
* DOES NOT MAKE USE OF EXPLICIT PIVOTING

In [14]:
import numpy as np

def rowOp(A, S):
    """
    Helper function to LU()
    Performs Row Swaps, according to Index Tuples in S
    INPUT:
    A: Numpy Matrix
    S: Numpy Matrix | Stores Row Swaps
    OUTPUT:
    A: Modified Matrix
    """
    # Modifying L, such that the Swaps are reversed, so as to give back the original Matrix, A
    # However, L is no longer Lower Triangular
    for j, i in S:
        A[[j, i]] = A[[i, j]]
        
    return A

def LU(A):
    """
    Returns LU Decomposition of A
    DEPENDENCY: rowOp()
    INPUT:
    A: Numpy Matrix | Matrix, to be decomposed
    OUTPUT:
    L: Numpy Matrix | Lower Triangular Factor of A
    U: Numpy Matrix | Upper Triangular Factor of A
    S: Numpy Matrix | Stores Row Swaps
    """
    n = A.shape[0]
    U = A.copy()
    L = np.identity(n)
    S = [] # List of Index Tuples | Stores swaps
    
    for i in range(n):
        lead = 0
        j = i
        while U[j][lead] == 0:
            j += 1
            if j == n:
                j = i
                lead += 1

        if j != i:
            U[[j, i]] = U[[i, j]] # Swapping rows
            S.append((j, i)) # Storing Swap

        for k in range(i+1, n):
            L[k, lead] = U[k, lead]/U[i, lead] # Storing coefficients in L
            U[k] = [kv - L[k, lead]*iv for kv, iv in zip(U[k], U[i])] # Modifying U

    if S: # S is non-empty
        print("WARNING: Swap Matrix, S, in non-empty.\nLU is no longer == A.\nUse S, along with rowOp() to modify L, in order to get LU == A (in which case, L will no longer be Lower Triangular).\nYou should also modify Vector B, similarly, if solving AX = B!\n")
    
    return L, U, S
    


# MODULE TEST
A = np.array([[0, 4, 2, 3],
              [0, 1, 4, 4],
              [-1, 0, 1, 0],
              [2, 0, 4, 1]], dtype=float)

l, u, s = LU(A)
L_FactorOfAButNotLowerTriangular, Lu = l.copy(), []


if s:
    L_FactorOfAButNotLowerTriangular = rowOp(L_FactorOfAButNotLowerTriangular, s) # RIP PEP Naming Schemes
    Lu = L_FactorOfAButNotLowerTriangular @ u # Should be == A

lu = l @ u # Matrix-multiplying l and u | Should NOT be == A, if S is non-empty

print("A = \n", A)
print("L = \n", l)
print("L_FactorOfAButNotLowerTriangular = \n", L_FactorOfAButNotLowerTriangular)
print("U = \n", u)
print("LU (Should NOT be == A) =\n", lu)
print("L_FactorOfAButNotLowerTriangular*U (Should be == A) =\n", Lu)

LU is no longer == A.
Use S, along with rowOp() to modify L, in order to get LU == A (in which case, L will no longer be Lower Triangular).
You should also modify Vector B, similarly, if solving AX = B!

A = 
 [[ 0.  4.  2.  3.]
 [ 0.  1.  4.  4.]
 [-1.  0.  1.  0.]
 [ 2.  0.  4.  1.]]
L = 
 [[ 1.          0.          0.          0.        ]
 [-0.          1.          0.          0.        ]
 [-0.          4.          1.          0.        ]
 [-2.          0.         -0.42857143  1.        ]]
L_FactorOfAButNotLowerTriangular = 
 [[-0.          4.          1.          0.        ]
 [-0.          1.          0.          0.        ]
 [ 1.          0.          0.          0.        ]
 [-2.          0.         -0.42857143  1.        ]]
U = 
 [[ -1.           0.           1.           0.        ]
 [  0.           1.           4.           4.        ]
 [  0.           0.         -14.         -13.        ]
 [  0.           0.           0.          -4.57142857]]
LU (Should NOT be == A) =
 [[-1. 

### LU Decomposition -  BONUS STUFF

* Linear Equation Solver (Using LU Decomposition)
* Determinant Calculation

In [10]:
# Linear Equation Solver
# Ax = b => LUx = rowOp(b) => First solve for Ly = rowOp(b), then Solve for Ux = y
# DEPENDENCY: rowOp()
A = np.array([[1., 0., 0., 0.],
              [5., 6., 0., 0.],
              [-4., 7., -2., 0.],
              [3., 2., -1., 4.]])

b = np.array([1., 4., -7., 20.])

L, U, S = LU(A)
L_FacNotlower = L.copy()

# Printing out the Solution is handled by back_sub() and forward_sub()
if S: # S is not empty
    L_FacNotlower = rowOp(L_FacNotlower, s) # RIP PEP Naming Schemes
    b = rowOp(b, S)
    y = forward_sub(L_FacNotlower, b, init_val=[1., 1., 1., 1.])
    x = back_sub(U, y, init_val=[1., 1., 1., 1.])
    
else:
    del L_FacNotlower # If S is empty, L_FacNotlower == L and so, L_FacNotLower is not needed
    y = forward_sub(L, b, init_val=[1., 1., 1., 1.])
    x = back_sub(U, y, init_val=[1., 1., 1., 1.])


SOLVER: FORWARD_SUB

System of Linear Equations:

1.0x0 + 0.0x1 + 0.0x2 + 0.0x3 = 1.0
5.0x0 + 1.0x1 + 0.0x2 + 0.0x3 = 4.0
-4.0x0 + 1.1666666666666667x1 + 1.0x2 + 0.0x3 = -7.0
3.0x0 + 0.3333333333333333x1 + 0.5x2 + 1.0x3 = 20.0

Iteration Limit:  100 

Iteration: 1 | Current Solution: [1.0, 1.0, 1.0, 1.0]
Iteration: 2 | Current Solution: [ 1.         -1.         -4.16666667 16.16666667]
Iteration: 3 | Current Solution: [ 1.         -1.         -1.83333333 19.41666667]
Iteration: 4 | Current Solution: [ 1.         -1.         -1.83333333 18.25      ]

Solution converged, after 3 iterations.

SOLUTION:  [ 1.         -1.         -1.83333333 18.25      ]
ERROR:  [0. 0. 0. 0.]

SOLVER: BACK_SUB

System of Linear Equations:

1.0x0 + 0.0x1 + 0.0x2 + 0.0x3 = 1.0
0.0x0 + 6.0x1 + 0.0x2 + 0.0x3 = -1.0
0.0x0 + 0.0x1 + -2.0x2 + 0.0x3 = -1.833333333333333
0.0x0 + 0.0x1 + 0.0x2 + 4.0x3 = 18.25

Iteration Limit:  100 

Iteration: 1 | Current Solution: [1.0, 1.0, 1.0, 1.0]
Iteration: 2 | Current Soluti

In [11]:
# Determinant Calculation
# Det(A) = Det(LU)*(-1)**(len(S))
# https://en.wikipedia.org/wiki/LU_decomposition#Computing_the_determinant
def DetLU(A):
    """
    Returns the determinant of A
    INPUT:
    A: Numpy Matrix | Matrix, whose determinant is to be calculated
    OUTPUT:
    det: Float | Determinant of A
    """
    L, U, S = LU(A) # Getting LU Decomposition of A
    n = A.shape[0]
    nS = len(S)
    det = 1
    for i in range(n):
        det *= L[i, i]*U[i, i]
    
    det *= (-1)**nS
    return det
       
print("Determinant of A = {}".format(DetLU(A)))
print("Determinant of A, using numpy.linalg.det = {}".format(np.linalg.det(A)))

Determinant of A = -48.0
Determinant of A, using numpy.linalg.det = -48.00000000000003


## 7. Inverse of a Matrix:

### Reference: https://integratedmlai.com/matrixinverse/

In [15]:
def Inv(A):
    """
    Returns Inverse of A
    DEPENDENCY: DetLU()
    INPUT:
    A: Numpy Matrix | Matrix, to be inverted
    OUTPUT:
    inv: Numpy Matrix | Inverse of A
    """
    # Prepping the Augmented Matrix
    n = A.shape[0]
    aug_mat = A.copy()
    
    inv = np.identity(n)
    
    # Input Checks
    if DetLU(A) == 0:
        print("WARNING: Determinant of this matrix = 0.\nERROR: Matrix cannot be inverted!")
        return None
    elif A.shape[0] != A.shape[1]:
        print("WARNING: Matrix is not a Square Matrix.\nERROR: Matrix cannot be inverted!")
        return None

    # Position of leading nonzero, nondiagonal-element in a row
    lead = 0
    
    for r in range(n):
        i = r
        
        # Finding the leading nonzero element in a column
        while aug_mat[i][lead] == 0:
            i += 1
            if i == n:
                i = r
                lead += 1
        
        aug_mat[[i, r]] = aug_mat[[r, i]] # Swapping rows
        inv[[i, r]] = inv[[r, i]] # Same operations to be performed on inv
        
        lv = aug_mat[r][lead]
        aug_mat[r] = [mrx / float(lv) for mrx in aug_mat[r]]
        inv[r] = [mrx / float(lv) for mrx in inv[r]]
        for i in range(n):
            if i != r:
                lv = aug_mat[i][lead]         
                aug_mat[i] = [iv - lv*rv for rv,iv in zip(aug_mat[r], aug_mat[i])]
                inv[i] = [iv - lv*rv for rv,iv in zip(inv[r], inv[i])]
        lead += 1
        
    return inv


# Testing the Procedure
A = np.array([[4., -1., 1.],
              [4., -8., 1.],
              [-2., 1., 5.]])

print("Inverse of A = \n", Inv(A))

print("A * Inv(A) = \n", Inv(A) @ A)

Inverse of A = 
 [[ 0.26623377 -0.03896104 -0.04545455]
 [ 0.14285714 -0.14285714  0.        ]
 [ 0.07792208  0.01298701  0.18181818]]
A * Inv(A) = 
 [[ 1.00000000e+00  1.38777878e-17 -4.16333634e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  0.00000000e+00  1.00000000e+00]]


## 8. Cholesky Decomposition
(From https://en.wikipedia.org/wiki/Cholesky_decomposition)

If we write out the equation:
$${\begin{aligned}\mathbf {A} =\mathbf {LL} ^{T}&={\begin{pmatrix}L_{11}&0&0\\L_{21}&L_{22}&0\\L_{31}&L_{32}&L_{33}\\\end{pmatrix}}{\begin{pmatrix}L_{11}&L_{21}&L_{31}\\0&L_{22}&L_{32}\\0&0&L_{33}\end{pmatrix}}\\&={\begin{pmatrix}L_{11}^{2}&&({\text{symmetric}})\\L_{21}L_{11}&L_{21}^{2}+L_{22}^{2}&\\L_{31}L_{11}&L_{31}L_{21}+L_{32}L_{22}&L_{31}^{2}+L_{32}^{2}+L_{33}^{2}\end{pmatrix}},\end{aligned}}$$

we obtain the following:

\begin{aligned}\mathbf {L} ={\begin{pmatrix}{\sqrt {A_{11}}}&0&0\\A_{21}/L_{11}&{\sqrt {A_{22}-L_{21}^{2}}}&0\\A_{31}/L_{11}&\left(A_{32}-L_{31}L_{21}\right)/L_{22}&{\sqrt {A_{33}-L_{31}^{2}-L_{32}^{2}}}\end{pmatrix}}\end{aligned}

and therefore the following formulas for the entries of L:

$$L_{j,j}={\sqrt {A_{j,j}-\sum _{k=1}^{j-1}L_{j,k}^{2}}}$$

$$L_{i,j}={\frac {1}{L_{j,j}}}\left(A_{i,j}-\sum _{k=1}^{j-1}L_{i,k}L_{j,k}\right)\quad {\text{for }}i>j$$

Cholesky Decomposition is usually twice as efficient as LU Decomposition

In [13]:
def choles_decomp(A):
    """
    Returns the Cholesky Factor of A
    DOES NOT CHECK FOR A's ELIGIBILITY TO BE CHOLESKY-DECOMPOSED
    INPUT:
    A: Numpy Matrix | Matix, to be decomposed
    OUTPUT:
    L: Numpy Matrix | Cholesky Factor of A
    """
    # L is the Cholesky Factor of A
    L = np.zeros_like(A)
    for i, (Ai, Li) in enumerate(zip(A, L)):
        for j, Lj in enumerate(L[:i+1]):
            s = sum(Li[k] * Lj[k] for k in range(j))
            Li[j] = np.sqrt(Ai[i] - s) if (i == j) else (1.0 / Lj[j] * (Ai[j] - s)) # Using the formulae from the description above

    print("Cholesky Factor:\n", L)

A = np.array([[1., 0.],
              [0., 5.]])

choles_decomp(A)

Cholesky Factor:
 [[1.         0.        ]
 [0.         2.23606798]]
